# Generated by Django 5.1.7 on 2025-03-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_date',
            field=models.IntegerField(default=1, max_length=30),
        ),
    ]
